<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.ProjectName.Dapper</AssemblyName>
    <PackageId>CompanyName.ProjectName.Dapper</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <OutputType>Library</OutputType>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\framework\src\CompanyName.Dapper.SqlServer\CompanyName.Dapper.SqlServer.csproj" />
  </ItemGroup>
  
	<ItemGroup>
	  <ProjectReference Include="..\CompanyName.ProjectName.Application\CompanyName.ProjectName.Application.csproj" />
	</ItemGroup>

</Project>
