<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Company>CompanyName</Company>
    <Authors></Authors>
    <Version>0.0.1</Version>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl></RepositoryUrl> 
  </PropertyGroup>

  <!--
  <Target Name="PostClean" AfterTargets="Clean">
    <RemoveDir Directories="$(BaseIntermediateOutputPath)" />
    <RemoveDir Directories="$(BaseOutputPath)" />
  </Target>
  -->
  
</Project>