<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Company>Verisure</Company>
    <Authors>Capgemini Engineering</Authors>
    <Version>1.0.0-rc</Version>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl></RepositoryUrl>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <!--
  <Target Name="PostClean" AfterTargets="Clean">
    <RemoveDir Directories="$(BaseIntermediateOutputPath)" />
    <RemoveDir Directories="$(BaseOutputPath)" />
  </Target>
  -->
  
</Project>
