<Project>

  <PropertyGroup>    
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EnableSourceLink>true</EnableSourceLink> 
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <Deterministic>true</Deterministic>
    <RootNamespace />
  </PropertyGroup>

  <!--<ItemGroup>
    <PackageReference Include="SourceLinkPackage" Version="SourceLinkVersion" PrivateAssets="All"/>
  </ItemGroup>-->

</Project>