<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.Ddd.Application</AssemblyName>
    <PackageId>CompanyName.Ddd.Application</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.AutoMapper\CompanyName.AutoMapper.csproj" />
    <ProjectReference Include="..\CompanyName.Ddd.Domain\CompanyName.Ddd.Domain.csproj" />
    <ProjectReference Include="..\CompanyName.Security\CompanyName.Security.csproj" />
    <ProjectReference Include="..\CompanyName.Localization\CompanyName.Localization.csproj" />
    <ProjectReference Include="..\CompanyName.Uow\CompanyName.Uow.csproj" />
  </ItemGroup>

</Project>
