<Project Sdk="Microsoft.NET.Sdk.Web">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.AspNetCore</AssemblyName>
    <PackageId>CompanyName.AspNetCore</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <OutputType>Library</OutputType>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'CompanyName.AspNetCore' " />
  <ItemGroup>
    <ProjectReference Include="..\CompanyName.Core\CompanyName.Core.csproj" />
    <ProjectReference Include="..\CompanyName.Security\CompanyName.Security.csproj" />
  </ItemGroup>

</Project>
