apiVersion: apps/v1
kind: Deployment
metadata:
  name: __NOMBRE_APP__-pod
  namespace: __NAMESPACE__
spec:
  replicas: __REPLICAS__
  selector:
    matchLabels:
      app: __NOMBRE_APP__-pod
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: __NOMBRE_APP__-pod
    spec:
      containers:
      - name: __NOMBRE_APP__-pod
        image: __dockerImage__
        env:
        - name: APPINSIGHTS__CONNECTIONSTRING
          value: __TFSET_Insight_Instumentation_Key__
        - name: defaultEndpointsProtocol
          value: __TFSET_STORAGE_CONNECTION_STRING__
        - name: Authentication__Authority
          value: __Authority__
        - name: Authentication__Audience
          value: __Audience__
        - name: Authentication__Scope
          value: __Scope__
        - name: Authentication__SwaggerClientId
          value: __SwaggerClientId__
        - name: Application__PathPrefix
          value: __PathPrefix__
        ports:
        - containerPort: __PUERTO_INTERNO__
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: __PUERTO_EXTERNO__
          initialDelaySeconds: 20
          periodSeconds: 60
          timeoutSeconds: 10
        readinessProbe: 
          failureThreshold: 3
          httpGet: 
            path: /self
            port: __PUERTO_EXTERNO__
          initialDelaySeconds: 25
          periodSeconds: 70
          timeoutSeconds: 15
        resources: 
          limits: 
            cpu: __LIMIT_CPU__
            memory: __LIMIT_MEMORY__
          requests: 
            cpu: __REQUEST_CPU__
            memory: __REQUEST_MEMORY__
      nodeSelector:
        beta.kubernetes.io/os: linux
