<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.EntityFrameworkCore</AssemblyName>
    <PackageId>CompanyName.EntityFrameworkCore</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.Auditing\CompanyName.Auditing.csproj" />
    <ProjectReference Include="..\CompanyName.Data\CompanyName.Data.csproj" />
    <ProjectReference Include="..\CompanyName.Ddd.Application\CompanyName.Ddd.Application.csproj" />
    <ProjectReference Include="..\CompanyName.EntityFrameworkCore.Abstractions\CompanyName.EntityFrameworkCore.Abstractions.csproj" />
    <ProjectReference Include="..\CompanyName.Uow\CompanyName.Uow.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CompanyName.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

</Project>
