<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>33b3c5cd-b507-47fa-a7ed-399e07f5a945</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <!--<PackageReference Include="Microsoft.ApplicationInsights.Kubernetes" />-->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"/>
    <PackageReference Include="Serilog.AspNetCore" />
    <!--<PackageReference Include="Serilog.Sinks.ApplicationInsights" />-->
    <!--<PackageReference Include="Serilog.Sinks.Async" />-->
    <PackageReference Include="CompanyName.Autofac" Condition="!$(Debug)" />
    <!--<PackageReference Include="CompanyName.ApplicationInsights.AspNetCore" Condition="!$(Debug)" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Autofac\CompanyName.Autofac.csproj" Condition="$(Debug)" />
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.ApplicationInsights.AspNetCore\CompanyName.ApplicationInsights.AspNetCore.csproj" Condition="$(Debug)" />  
    <ProjectReference Include="..\CompanyName.Banks.Api\CompanyName.Banks.Api.csproj" />
  </ItemGroup>

</Project>
