<Project>

	<PropertyGroup>
        <TargetFramework>TargetFrameworkOverride</TargetFramework>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<CompanyNameVersion>1.0.0</CompanyNameVersion>
		<Debug>True</Debug>
		<RootNamespace>Samples.Banks</RootNamespace>
	</PropertyGroup>

</Project>