<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" />
    <!--<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />-->
    <!--<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" />-->
    <!--<PackageReference Include="Swashbuckle.AspNetCore" />-->
    <PackageReference Include="CompanyName.AspNetCore.Mvc" Condition="!$(Debug)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.AspNetCore.Mvc\CompanyName.AspNetCore.Mvc.csproj" Condition="$(Debug)"/>
    <ProjectReference Include="..\CompanyName.Banks.Application\CompanyName.Banks.Application.csproj" />
  </ItemGroup>

</Project>
