<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CompanyName.Core" Condition="!$(Debug)" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Core\CompanyName.Core.csproj" Condition="$(Debug)" />
  </ItemGroup> 
</Project>
