# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Directory.Packages.props", "."]
COPY ["Directory.Build.props", "."]
COPY ["nuget.config", "."]
COPY ["src/Samples.Banks.HttpApi.Host/Samples.Banks.HttpApi.Host.csproj", "src/Samples.Banks.HttpApi.Host/"]
COPY ["src/Samples.Banks.Dapper/Samples.Banks.Dapper.csproj", "src/Samples.Banks.Dapper/"]
COPY ["src/Samples.Banks.Application/Samples.Banks.Application.csproj", "src/Samples.Banks.Application/"]
COPY ["src/Samples.Banks.Domain/Samples.Banks.Domain.csproj", "src/Samples.Banks.Domain/"]
COPY ["src/Samples.Banks.Domain.Shared/Samples.Banks.Domain.Shared.csproj", "src/Samples.Banks.Domain.Shared/"]
COPY ["src/Samples.Banks.EntityFrameworkCore/Samples.Banks.EntityFrameworkCore.csproj", "src/Samples.Banks.EntityFrameworkCore/"]
COPY ["src/Samples.Banks.HttpApi/Samples.Banks.HttpApi.csproj", "src/Samples.Banks.HttpApi/"]
RUN dotnet restore "./src/Samples.Banks.HttpApi.Host/Samples.Banks.HttpApi.Host.csproj"
COPY . .
WORKDIR "/src/src/Samples.Banks.HttpApi.Host"
RUN dotnet build "./Samples.Banks.HttpApi.Host.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Samples.Banks.HttpApi.Host.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Samples.Banks.HttpApi.Host.dll"]