<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.ProjectName.EntityFrameworkCore</AssemblyName>
    <PackageId>CompanyName.ProjectName.EntityFrameworkCore</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <OutputType>Library</OutputType>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\framework\src\CompanyName.EntityFrameworkCore.SqlServer\CompanyName.EntityFrameworkCore.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.ProjectName.Application\CompanyName.ProjectName.Application.csproj" />
  </ItemGroup>

</Project>
