<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ed1fa7eb-5449-46c6-94f3-2de4aa7d75ac</UserSecretsId>
    <Dockerfile>Dockerfile.dev</Dockerfile>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Compile Remove="Settings\**" />
    <Content Remove="Logs\**" />
    <Content Remove="Settings\**" />
    <EmbeddedResource Remove="Logs\**" />
    <EmbeddedResource Remove="Settings\**" />
    <None Remove="Logs\**" />
    <None Remove="Settings\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.ApplicationStatus" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
    <PackageReference Include="Serilog.Extensions.Logging.File" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CompanyName.Autofac" Condition="!$(Debug)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Autofac\CompanyName.Autofac.csproj" Condition="$(Debug)" />
    <ProjectReference Include="..\Samples.Banks.Dapper\Samples.Banks.Dapper.csproj" />
    <ProjectReference Include="..\Samples.Banks.EntityFrameworkCore\Samples.Banks.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\Samples.Banks.HttpApi\Samples.Banks.HttpApi.csproj" />
  </ItemGroup>

</Project>
