<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CompanyName.Ddd.Domain.EventBus" Condition="!$(Debug)" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Ddd.Domain.EventBus\CompanyName.Ddd.Domain.EventBus.csproj" Condition="$(Debug)" />
  </ItemGroup> 
</Project>
