<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
		<PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CompanyName.EntityFrameworkCore.SqlServer" Condition="!$(Debug)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\framework1\src\CompanyName.EntityFrameworkCore.SqlServer\CompanyName.EntityFrameworkCore.SqlServer.csproj" Condition="$(Debug)" />
		<ProjectReference Include="..\Samples.Banks.Application\Samples.Banks.Application.csproj" />
	</ItemGroup>

</Project>

