<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.TestBase</AssemblyName>
    <PackageId>CompanyName.TestBase</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.Autofac\CompanyName.Autofac.csproj" />
    <ProjectReference Include="..\CompanyName.EntityFrameworkCore\CompanyName.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
