<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\CompanyName.Banks.Domain\CompanyName.Banks.Domain.csproj" />
    <ProjectReference Include="..\CompanyName.Banks.EntityFrameworkCore.SqlServer.Tests\CompanyName.Banks.EntityFrameworkCore.SqlServer.Tests.csproj" />
  </ItemGroup>

</Project>
