<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.ProjectName.Domain</AssemblyName>
    <PackageId>CompanyName.ProjectName.Domain</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <OutputType>Library</OutputType>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\..\framework1\src\CompanyName.Ddd.Domain\CompanyName.Ddd.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\framework\src\CompanyName.Ddd.Domain.Eventing\CompanyName.Ddd.Domain.Eventing.csproj" />
    <ProjectReference Include="..\..\..\..\..\..\..\framework1\src\CompanyName.Localization\CompanyName.Localization.csproj" />
    <ProjectReference Include="..\CompanyName.ProjectName.Domain.Shared\CompanyName.ProjectName.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CompanyName\ProjectName\Resources\ProjectNameResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProjectNameResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="CompanyName\ProjectName\Resources\ProjectNameResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ProjectNameResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace>CompanyName.ProjectName.Resources</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
