<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CompanyName.Ddd.Application" Version="$(CompanyNamePackageVersion)"  />
    <PackageReference Include="CompanyName.Caching.StackExchangeRedis" Version="$(CompanyNamePackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.ProjectName.Domain\CompanyName.ProjectName.Domain.csproj" />
    <ProjectReference Include="..\CompanyName.ProjectName.EntityFrameworkCore.SqlServer\CompanyName.ProjectName.EntityFrameworkCore.SqlServer.csproj" />
  </ItemGroup>

</Project>
