<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum" />
    <PackageReference Include="FluentResults" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CompanyName.Ddd.Domain" Condition="!$(Debug)" />
    <PackageReference Include="CompanyName.Ddd.Domain.EventBus" Condition="!$(Debug)" />
    <PackageReference Include="CompanyName.EventBus.AzureServiceBus" Condition="!$(Debug)" />
    <PackageReference Include="CompanyName.Localization" Condition="!$(Debug)" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Ddd.Domain\CompanyName.Ddd.Domain.csproj" Condition="$(Debug)" />
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Ddd.Domain.EventBus\CompanyName.Ddd.Domain.EventBus.csproj" Condition="$(Debug)" />
	<ProjectReference Include="..\..\..\..\framework\src\CompanyName.EventBus.AzureServiceBus\CompanyName.EventBus.AzureServiceBus.csproj" Condition="$(Debug)" />
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Localization\CompanyName.Localization.csproj" Condition="$(Debug)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Samples.Banks.Domain.Shared\Samples.Banks.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\BanksResource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BanksResource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\BanksResource.en.resx">
      <Generator></Generator>
      <CustomToolNamespace></CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\BanksResource.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BanksResource.Designer.cs</LastGenOutput>
      <CustomToolNamespace></CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

</Project>
