<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.Autofac</AssemblyName>
    <PackageId>CompanyName.Autofac</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac"  />
    <PackageReference Include="Autofac.Extensions.DependencyInjection"  />
    <PackageReference Include="Autofac.Extras.DynamicProxy"  />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.Core\CompanyName.Core.csproj" />
  </ItemGroup>

</Project>
