apiVersion: v1
kind: Service
metadata:
  name: __NOMBRE_APP__-service
  namespace: __NAMESPACE__
spec:
  type: ClusterIP
  ports:
  - port: __PUERTO_EXTERNO__
    targetPort: __PUERTO_INTERNO__
  selector:
    app: __NOMBRE_APP__-pod