<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.EntityFrameworkCore.Abstracts</AssemblyName>
    <PackageId>CompanyName.EntityFrameworkCore.Abstracts</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="$(MicrosoftPackageVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.Core\CompanyName.Core.csproj" />
  </ItemGroup>
  
</Project>
