<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Validators\**" />
    <EmbeddedResource Remove="Validators\**" />
    <None Remove="Validators\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults.Extensions.AspNetCore" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CompanyName.AspNetCore.Mvc" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CompanyName.ProjectName.Application\CompanyName.ProjectName.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Endpoints\Shared\" />
	</ItemGroup>

</Project>