<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\packages.props" />

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.Core</AssemblyName>
    <PackageId>CompanyName.Core</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Diagnostics" />
    <PackageReference Include="Nito.AsyncEx" />
    <PackageReference Include="LazyProxy.ServiceProvider"  />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder"  />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Configuration"  />
    <PackageReference Include="Microsoft.Extensions.Logging"  />
  </ItemGroup>
  
</Project>