<Project>

  <PropertyGroup>
    <TargetFramework>TargetFrameworkOverride</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>0.0.1</Version>
    <CompanyNameVersion>1.0.0-rc20260109</CompanyNameVersion>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RootNamespace>CompanyName.ProjectName</RootNamespace>
  </PropertyGroup>

</Project>