<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CompanyName.Dapper.SqlServer" Version="$(Version)" Condition="!$(Debug)" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\src\CompanyName.Dapper.SqlServer\CompanyName.Dapper.SqlServer.csproj" Condition="$(Debug)" />
    <ProjectReference Include="..\CompanyName.Banks.Domain\CompanyName.Banks.Domain.csproj" />
  </ItemGroup>
  
</Project>
