<Project Sdk="Microsoft.NET.Sdk">

  
  <Import Project="..\..\..\packages.props" />
  
  <PropertyGroup> 
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <AssemblyName>CompanyName.ServiceBus.Azure</AssemblyName>
    <PackageId>CompanyName.ServiceBus.Azure</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompanyName.Core\CompanyName.Core.csproj" />
    <ProjectReference Include="..\CompanyName.ServiceBus.Abstractions\CompanyName.ServiceBus.Abstractions.csproj" />
  </ItemGroup>
  
</Project>
